[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bibly"
version = "0.0.1"
authors = [
  { name="Nils A. Herrmann de Alba", email="nils_herrmann@outlook.de" },
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["pybliometrics", "sprynger"]
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.setuptools.packages.find]
include = ["sprynger", "sprynger.*"]
